name: AdamBallDC
favicon: null
layout_spectrum: 0.90648
typography_spectrum: 0.29964082478545606
title: 'In constant pursuit of health, performance and longevity'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0c0c'
    - '#7c8da1'
    - '#47464b'
    - '#dcb993'
    - '#ca6635'
  brandStrength: 0.625
  lightness: 0.6449972449336201
  saturation: 0.3125
  rhythmicContrast: 0.3041337882168591
purpose: []
