name: AdamBallDC
favicon: null
layout_spectrum: 0.2945499604102224
typography_spectrum: 0.29964082478545606
title: 'In constant pursuit of health, performance and longevity'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3461258776951581
  lightness: 0.6449972449336201
  saturation: 0.9807449660729617
  rhythmicContrast: 0.3041337882168591
purpose: []
